name: swipeable_page_route_example
description: "Example for 🔙 swipeable_page_route, a package adding back-navigation by swiping with beatifully morphing widgets"
version: 0.1.6

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  swipeable_page_route:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
