name: swipeable_page_route_example
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  swipeable_page_route:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
