name: swipeable_page_route_example
description: 'Example for 🔙 swipeable_page_route, a package adding back-navigation by swiping with beatifully morphing widgets'
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  swipeable_page_route:
    path: ../

flutter:
  uses-material-design: true
