name: swipeable_page_route
description: "🔙 Swipe to navigate back and admire beautifully morphing widgets"
version: 0.0.1
homepage: https://github.com/JonasWanke/swipeable_page_route

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  black_hole_flutter: ^0.2.9
  dartx: ^0.2.0
  list_diff: ^1.3.0
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
