name: swipeable_page_route
description: '🔙 Swipe to navigate back and admire beautifully morphing widgets'
version: 0.2.4
homepage: https://github.com/JonasWanke/swipeable_page_route

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  black_hole_flutter: ^0.3.0
  collection: ^1.15.0
  flutter:
    sdk: flutter
  list_diff: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
