name: swipeable_page_route
description: "🔙 Swipe to navigate back and admire beautifully morphing widgets"
version: 0.1.6
homepage: https://github.com/JonasWanke/swipeable_page_route

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  black_hole_flutter: ^0.2.10
  dartx: ^0.5.0
  flutter:
    sdk: flutter
  list_diff: ^1.3.0
  meta: ^1.1.8

dev_dependencies:
  extra_pedantic: ^1.2.0
  test: ^1.9.4
